version: '3.8'

services:
  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: odoo:16.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    networks:
      - odoo-network

volumes:
  odoo-db-data:
  odoo-data:

networks:
  odoo-network:
    driver: bridge